name: Ruby

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ matrix.os }}-ruby-version-${{ matrix.ruby }}-gems-${{ hashFiles('**/*[Gg]em[fs][ip][le][ec]') }}
        restore-keys: |
          ${{ matrix.os }}-ruby-version-${{ matrix.ruby }}-gems-

    - name: Install dependencies
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Test with RSpec
      run: |
        bundle exec rspec spec
